server:
  port: 8765

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:binance.db
    username:
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

mybatis:
  type-aliases-package: com.example.binance.entity
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 注释或删除

logging:
  level:
    org.springframework.jdbc.datasource: WARN
    org.mybatis.spring: WARN
    org.apache.ibatis: WARN